!MODULE sys_par
!IMPLICIT NONE
!INTEGER,PARAMETER:: double=8
!INTEGER,DIMENSION(2,3),PARAMETER::mat=(/1,2,3,4,5,6/)
!REAL(KIND=double),PARAMETER::pi=3.1415
!REAL(KIND=double),DIMENSION(2),PARAMETER::a2star=(/0.*5,pi/)
!END MODULE sys_par

PROGRAM MAIN
!USE sys_par
IMPLICIT NONE
complex(KIND=8)::a
 write(*,*) tiny(a) 
END PROGRAM MAIN


